//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRUNG;Initial Catalog=Hanoiguesthouses;User ID=sa;Password=123456789")]
        public string HanoiguesthousesConnectionString {
            get {
                return ((string)(this["HanoiguesthousesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TeamplateHotel;User ID=sa;Password=1234567" +
            "")]
        public string HanoiCityHotelConnectionString {
            get {
                return ((string)(this["HanoiCityHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=HaNoiCityPlaceHotel;Persist Security Info=" +
            "True;User ID=sa;Password=1234567")]
        public string HaNoiCityPlaceHotelConnectionString {
            get {
                return ((string)(this["HaNoiCityPlaceHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=EssenceHanoi;User ID=sa;Password=1234567")]
        public string EssenceHanoiConnectionString {
            get {
                return ((string)(this["EssenceHanoiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUNG-PC\\MANH;Initial Catalog=TeamplateHotel_25082014;User ID=sa;Passw" +
            "ord=123456")]
        public string TeamplateHotel_25082014ConnectionString {
            get {
                return ((string)(this["TeamplateHotel_25082014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUNG-PC\\MANH;Initial Catalog=TeamplateHotel;User ID=sa;Password=12345" +
            "6")]
        public string TeamplateHotelConnectionString {
            get {
                return ((string)(this["TeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TestTeamplateHotel;User ID=sa;Password=123" +
            "4567")]
        public string TestTeamplateHotelConnectionString {
            get {
                return ((string)(this["TestTeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TeamplateHotel29112014;User ID=sa;Password" +
            "=1234567")]
        public string TeamplateHotel29112014ConnectionString {
            get {
                return ((string)(this["TeamplateHotel29112014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=DbTestTeamplateHotel;User ID=sa;Password=1" +
            "234567")]
        public string DbTestTeamplateHotelConnectionString {
            get {
                return ((string)(this["DbTestTeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC\\WEBHOTEL;Initial Catalog=DemoWebhotel;Integrated Securit" +
            "y=True")]
        public string DemoWebhotelConnectionString {
            get {
                return ((string)(this["DemoWebhotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.27.60.26;Initial Catalog=DemoWebhotel;User ID=DemoWebhotel;Passwo" +
            "rd=DemoWebhotel@123465")]
        public string DemoWebhotelConnectionString1 {
            get {
                return ((string)(this["DemoWebhotelConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CMLVIETNAM;Initial Catalog=BienBachotel;User ID=sa;Pa" +
            "ssword=abc@123")]
        public string BienBachotelConnectionString {
            get {
                return ((string)(this["BienBachotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CMLVIETNAM;Initial Catalog=TeamplateHotel_NoBe;User I" +
            "D=sa;Password=abc@123")]
        public string TeamplateHotel_NoBeConnectionString {
            get {
                return ((string)(this["TeamplateHotel_NoBeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CML_SERVER;Initial Catalog=TeamplateHotel_NoBE;User I" +
            "D=sa;Password=abc@123")]
        public string TeamplateHotel_NoBEConnectionString1 {
            get {
                return ((string)(this["TeamplateHotel_NoBEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CML_SERVER;Initial Catalog=HoianSalemRiverSide;User I" +
            "D=sa;Password=abc@123")]
        public string HoianSalemRiverSideConnectionString {
            get {
                return ((string)(this["HoianSalemRiverSideConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHAMPHUONG-PC\\SQLEXPRESS;Initial Catalog=TeamplateHotel_NoBE;Persist " +
            "Security Info=True;User ID=sa;Password=123456")]
        public string TeamplateHotel_NoBEConnectionString2 {
            get {
                return ((string)(this["TeamplateHotel_NoBEConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHUONG-PC;Initial Catalog=DBRoost;Integrated Security=True")]
        public string DBRoostConnectionString {
            get {
                return ((string)(this["DBRoostConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SKSDLCB\\SQLEXPRESS;Initial Catalog=DBRoost;Integrated Securit" +
            "y=True")]
        public string DBRoostConnectionString1 {
            get {
                return ((string)(this["DBRoostConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-38AJ5FV\\MSSQLSERVER01;Initial Catalog=ThienAn_Hotel;Integrate" +
            "d Security=True")]
        public string ThienAn_HotelConnectionString {
            get {
                return ((string)(this["ThienAn_HotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.226.248.52;Initial Catalog=webkhachhang_thienanhotel;User ID=webk" +
            "h_thienanhotel;Password=123456789a@@")]
        public string webkhachhang_thienanhotelConnectionString {
            get {
                return ((string)(this["webkhachhang_thienanhotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CCASMKP\\SQLEXPRESS;Initial Catalog=webkhachhang_thienanhotel;" +
            "Integrated Security=True;Encrypt=True;TrustServerCertificate=True")]
        public string webkhachhang_thienanhotelConnectionString1 {
            get {
                return ((string)(this["webkhachhang_thienanhotelConnectionString1"]));
            }
        }
    }
}
