//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        internal static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        internal static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival With Flight.
        /// </summary>
        internal static string ArrivalWithFlight {
            get {
                return ResourceManager.GetString("ArrivalWithFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Tour.
        /// </summary>
        internal static string BookingTour {
            get {
                return ResourceManager.GetString("BookingTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Tour.
        /// </summary>
        internal static string BookTour {
            get {
                return ResourceManager.GetString("BookTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability.
        /// </summary>
        internal static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Master&apos;s Rooms.
        /// </summary>
        internal static string HotelMasterRooms {
            get {
                return ResourceManager.GetString("HotelMasterRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER SERVICES.
        /// </summary>
        internal static string HOTELSERVICES {
            get {
                return ResourceManager.GetString("HOTELSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I read and agree with the agreemens and conditions of the .
        /// </summary>
        internal static string Igree {
            get {
                return ResourceManager.GetString("Igree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Room.
        /// </summary>
        internal static string InfoRoom {
            get {
                return ResourceManager.GetString("InfoRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Map.
        /// </summary>
        internal static string LocationMap {
            get {
                return ResourceManager.GetString("LocationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A Reservation.
        /// </summary>
        internal static string MakeAReservation {
            get {
                return ResourceManager.GetString("MakeAReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max People.
        /// </summary>
        internal static string MaxPeople {
            get {
                return ResourceManager.GetString("MaxPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Rooms.
        /// </summary>
        internal static string NameRooms {
            get {
                return ResourceManager.GetString("NameRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Tripadvisor.
        /// </summary>
        internal static string OnTripadvisor {
            get {
                return ResourceManager.GetString("OnTripadvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orther Request.
        /// </summary>
        internal static string OrtherRequest {
            get {
                return ResourceManager.GetString("OrtherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Articles.
        /// </summary>
        internal static string OtherArticles {
            get {
                return ResourceManager.GetString("OtherArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Rooms.
        /// </summary>
        internal static string OtherRooms {
            get {
                return ResourceManager.GetString("OtherRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Services.
        /// </summary>
        internal static string OtherServices {
            get {
                return ResourceManager.GetString("OtherServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tours.
        /// </summary>
        internal static string OtherTours {
            get {
                return ResourceManager.GetString("OtherTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKAGES &amp; OFFERS.
        /// </summary>
        internal static string PACKAGESOFFERS {
            get {
                return ResourceManager.GetString("PACKAGESOFFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power by.
        /// </summary>
        internal static string PowerBy {
            get {
                return ResourceManager.GetString("PowerBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Night.
        /// </summary>
        internal static string PriceNight {
            get {
                return ResourceManager.GetString("PriceNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Availability.
        /// </summary>
        internal static string SearchAvailability {
            get {
                return ResourceManager.GetString("SearchAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        internal static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL PACKAGE.
        /// </summary>
        internal static string SPECIALPACKAGE {
            get {
                return ResourceManager.GetString("SPECIALPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ur.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams &amp; Conditions.
        /// </summary>
        internal static string TeamsConditions {
            get {
                return ResourceManager.GetString("TeamsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Information.
        /// </summary>
        internal static string TourInformation {
            get {
                return ResourceManager.GetString("TourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripAdvisor.
        /// </summary>
        internal static string TripAdvisor {
            get {
                return ResourceManager.GetString("TripAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAll.
        /// </summary>
        internal static string Viewall {
            get {
                return ResourceManager.GetString("Viewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Rooms.
        /// </summary>
        internal static string ViewAllRoom {
            get {
                return ResourceManager.GetString("ViewAllRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail.
        /// </summary>
        internal static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW RATES FOR ALL ROOMS HERE.
        /// </summary>
        internal static string VIEWRATES {
            get {
                return ResourceManager.GetString("VIEWRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Room Details.
        /// </summary>
        internal static string ViewRoomDetails {
            get {
                return ResourceManager.GetString("ViewRoomDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information.
        /// </summary>
        internal static string YourInformation {
            get {
                return ResourceManager.GetString("YourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Requests.
        /// </summary>
        internal static string YourRequests {
            get {
                return ResourceManager.GetString("YourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Reservation.
        /// </summary>
        internal static string YourReservation {
            get {
                return ResourceManager.GetString("YourReservation", resourceCulture);
            }
        }
    }
}
